version: "3"

services:
  golang:
    container_name: chetoru_golang_container
    environment:
      TZ: Europe/Moscow
      PG_HOST: ${PG_HOST}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB_NAME: ${PG_DB_NAME}
      PG_PORT: ${PG_PORT}
      REDIS_ADDR: redis:6379
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      TG_ADMIN_ID: ${TG_ADMIN_ID}
    build: .
    ports:
      - "8081:8081"
    networks:
      - internal-network
    restart: unless-stopped

  redis:
    container_name: chetoru_redis_container
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
    networks:
      - internal-network
    restart: unless-stopped

networks:
  internal-network:
    driver: bridge

volumes:
  redis_data: