-- +goose Up
-- +goose StatementBegin
-- SQLite doesn't support dropping unique constraints directly
-- This migration is effectively a no-op for SQLite
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- SQLite doesn't support adding unique constraints directly
-- This migration is effectively a no-op for SQLite
-- +goose StatementEnd
