name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up SSH
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.10.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Deploy to VPS
    - name: Deploy to VPS
      run: ssh -o StrictHostKeyChecking=no root@213.139.211.120 "/root/scripts/run_chetoru.sh"
